version: '2'
services:
        web:
                build:
                        context: ./
                        dockerfile: web.docker
                
                container_name: web
                ports: 
                        - "127.0.0.1:8080:80"
                volumes: 
                        - ./:/var/www
                links: 
                        - app
        app: 
                build: 
                        context: ./
                        dockerfile: app.docker

                volumes: 
                        - ./:/var/www
                depends_on: 
                        - mysql
                        - redis
      
        mysql:  -
                image: mysql:5.7
                environment: 
                        MYSQL_DATABASE: ${DB_DATABASE}
                        MYSQL_USER:     ${DB_USERNAME}
                        MYSQL_PASSWORD: ${DB_PASSWORD}
                volumes: 
                        - ./mysql:/var/lib/mysql
        

        redis: 
                image: redis:3.0
       
                volumes: 
                        - ./redis:/data
